# Generated by Django 4.2.4 on 2023-09-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='datauser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=60)),
                ('lname', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('phone', models.CharField(default=' ', max_length=10)),
            ],
        ),
    ]
