# Generated by Django 4.2.4 on 2023-09-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_buy2_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy2',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
